name: build

on:
  push:
env:
  PAWPAW_SKIP_LV2: 0

jobs:
  linux:
    strategy:
      matrix:
        target: [linux-x86_64]
    runs-on: ubuntu-20.04
    permissions:
        contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: ./.github/actions
        with:
          target: ${{ matrix.target }}
          extraargs: SSE_CFLAGS="" FFT_FLAG=""
          pawpaw: true

  arm64:
    strategy:
      matrix:
        target: [linux-arm64]
    runs-on: ubuntu-20.04
    permissions:
        contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: ./.github/actions
        with:
          target: ${{ matrix.target }}
          pawpaw: true

  linux-optimised:
    strategy:
      matrix:
        target: [linux-x86_64]
    runs-on: ubuntu-latest
    permissions:
        contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: ./.github/actions
        with:
          target: ${{ matrix.target }}
          postfix: -v3
          lto: true
          pawpaw: true

  windows:
    strategy:
      matrix:
        target: [win64]
    runs-on: ubuntu-latest
    permissions:
        contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: ./.github/actions
        with:
          target: ${{ matrix.target }}
          lto: true
          pawpaw: true

  source:
    runs-on: ubuntu-20.04
    permissions:
        contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: ./.github/actions
        with:
          target: source

